version: 2

sources:
    - name: staging
      #For bigquery:
      #database: taxi-rides-ny-339813

      # For postgres:
      database: round-honor-373909

      schema: yield_staging

      # loaded_at_field: record_loaded_at
      tables:
        - name: geo_coord
        - name: wheat
        - name: maize
         # freshness:
           # error_after: {count: 6, period: hour}